### ISSUE TITLE
Fix Encapsulation Problem

### ISSUE THREAD

**Issue by yenjungw** [CMU-17-214/f2023#12]
(1) The location of the problem code:
In project/Image.java, Metadata Class, Topic Class, the classes exist attributes that can be directly accessed and possibly modified by others.

(2) Reasons for why the code is a problem:
**- [Violation of Encapsulation]**
Partial attributes in the three classes is public. This means any class can directly access this attribute. Although it's declared as final (which means you can't change the reference to another map), the contents of the map can still be modified since the object itself is mutable.

**Comment by jlacomis** [comment]
https://github.com/CMU-17-214/f2023/issues/8#issuecomment-1775328722
